export const en = {
  scene1: {
    title: "Scene 1: Welcoming the new space monkey",
    text1: `— So, astronaut, you finally made it. Your trips to IKEA don’t matter anymore. The issue isn’t that you once bought an extra shelf. The issue is that while you were caught up in the details of rent and credit, they’ve already pulled one over on you. Twice.`,
    text2: `— You think you're in control of your life. In reality, all these discounts, new gadgets, and "personalized" offers are just a way to keep you on a leash. They know what you'll do tomorrow, which means, to them, you're simply a predictable and  valuable resource.`,
    text3: `— But here’s the thing: even if you become the one giving the orders, you’ll still be part of the system. Shepherd or sheep — the roles may differ, but the rules stay the same.`,
    text4: `— The real choice isn’t about climbing higher; it’s about leaving the game entirely. It’s not about power — it’s about freedom. Almost like breaking out of samsara. If you’re tired of living in this loop, welcome to cyberpunk.`,
    text5: `— Here's your first step. Sign this. A digital signature — and you're with us.`,
    desc: `*Use your account with an activated season pass to sign a message with the text "\`I'm a space monkey!\`". You can use the [MetaMask](https://metamask.io/) app and the message signing service from [Etherscan](https://etherscan.io/verifiedSignatures) for this.*`,
    button: "Send Tyler a signed message",
    text7:
      "— Signed — means you’re in. From here, we’ll see how far you can go. The fight isn’t with someone else — it’s with yourself.",
    button_next: "Next scene",
    text8: "Please enter your address in mainnet.",
    error1: "The address specified is not valid",
    error2: "The pass has already been activated",
    error3: "You don't have an activated pass",
    error4: "The pass is not valid",
    text9: "Enter the hash of the signed message",
    exit: "Exit",
  },
  scene2: {
    title: "Scene 2: Tyler escorts to the first location",
    text1: `— Alright, astronaut. You're in Bangkok, and it’s a great chance to dive into the basics of cyberpunk.  Sure, it's not Chiba City, but here, freedom echoes around every corner.`,
    text2: `— Haven't read Neuromancer or played Cyberpunk? No? Okay, no big deal. Just don’t bluescreen. Let’s start simple: go to a bar and do something you’ve never tried before.`,
    text3: `— Here’s the location https://maps.app.goo.gl/FmFBpJWwWAGNVgMa8 . Once you get there, order yourself a drink. Then show the bartender your season pass — he'll give you instructions for all three locations.`,
    text4: `— As soon as you’re seated with the stuff from the bartender, let me know right away.`,
    button: "I'm in a bar",
    group: "Contact the quest control center",
    error: "Busy. Try again later.",
  },
  scene3: {
    title: `Scene 3: At the bar “Midlife Crisis”`,
    text1: `— A funny place. A midlife crisis. Instead of Afterlife, to which the street kids, exhausted by the metropolis, once sought, we have a loosely knotted tie on the neck of a tortured, honest taxpayer. Сomedy and tragedy at the same time.`,
    text2: `— This bar is our portal. More precisely, the restroom in this bar.`,
    text3: `— Go into the toilet and look around. There will be a leak sensor, as in the instructions. You need to close its contacts.`,
    text4: `— You can lick it. Or come up with something smarter — it’s your call.`,
    text5: `— Once you do that, I’ll see the signal on my frequency and send you the coordinates for the next location. There, you'll find a special braindance featuring the events of a certain massage room.`,
    finish: `— Looks like you did it! Here are the coordinates for the next location: 13.7216119,100.5648836 https://maps.app.goo.gl/zSq5HqQHHCfuUYjQ8\nIn Robonomics: https://robonomics.subscan.io/extrinsic/__blockNumber__-__txIndex__`,
  },
  scene4: {
    title: `Сцена 4: По пути в массажный салон`,
    text1: `— Here’s an interesting historical fact: when that infamous conflict was raging on the nearby peninsula —the one Kubrick depicted in Full Metal Jacket — some of the brave soldiers fighting there were stationed nearby, in Pattaya. They liked it so much that, a decade later, sex tourism in Thailand was thriving like never before.`,
    text2: `— And now it’s become even simpler: 4- and 5-star hotels, and on Sukhumvit, girls stand along the road. Just shake her hand — and she’s yours, do whatever you want. All funded by investors' money, of course.`,
    text3: `— You know what’s especially cringeworthy? Pattaya is now a hangout not only for tourists looking for sex, but also for married guys from post-Soviet countries. Imagine the reaction of an Englishman when he finds out that a Belarusian or Kazakh is coming here with his wife and three children? Paradoxes, plain and simple.`,
    text4: `— Alright, let's get down to business. You need to get into a massage parlor of my friend's. Show your season pass at the entrance, and she’ll guide you to a special room. No one works in that room anymore, but one interesting story has been preserved within its walls. You’ll have to see it for yourself.`,
    text5: `— Before you enter, the parlor needs to be activated. The owner is a decent woman, so don't think of the place as a jerk-off point. Message me when you're 15 minutes away from the spot, and I'll check that there won't be anyone extra there.  You should be met and shown in within 30 minutes.`,
    button: "Activate location for 45 min",
    group: "Contact the quest control center",
    error: "Busy. Try again later.",
    activated:
      "The location is activated. You have the coordinates. Show your season pass at the entrance. Don’t delay.",
    finish: `— Looks like you did it! \nIn Robonomics: https://robonomics.subscan.io/extrinsic/__blockNumber__-__txIndex__`,
    // finish: `— Looks like you did it! Here are the coordinates for the next location: 13.7176564,100.5668314\nIn Robonomics: https://robonomics.subscan.io/extrinsic/__blockNumber__-__txIndex__`,
  },
  scene5: {
    title: `The next location will be available tomorrow.`,
  },
};
